version: "3.9"

services:

  uptime-kuma:
    image: 'louislam/uptime-kuma:latest'
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - './uptime-kuma:/app/data'
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime.ozeliurs.com`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=cloudflare"
    dns:
      - 1.1.1.1
      - 8.8.8.8

networks:
  traefik:
    external: true